name: DEV APP Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [none]


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint & Auto-fix
        run: npm run lint:fix

      - name: Check Formatting
        run: npm run format:check

      - name: Run Tests
        run: npm run test

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      APP_DIRECTORY: ${{ vars.APP_DIRECTORY }}
      BRANCH: 'main'

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Pull Latest Code
        run: |
          ssh $SSH_USER@$SSH_HOST << EOF
            cd $APP_DIRECTORY
            git reset --hard
            git fetch
            git checkout $BRANCH
            git pull origin $BRANCH
          EOF

      - name: Build and Deploy
        run: |
          ssh $SSH_USER@$SSH_HOST << EOF
            cd $APP_DIRECTORY
            npm install
            npm run build
            pm2 restart all
          EOF
          
  





      
